version: "3"
services:
  rstudio:
    build: .
    environment:
      - PASSWORD=${RSTUDIO_PASSWORD}
    ports:
      - "8787:8787"
    volumes:
      - ./src:/home/rstudio
      - ./lib/global:/usr/local/lib/R/site-library
      - ./lib/renv:/home/rstudio/renv/library
